# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/AddFolder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobufs import MessageComponents_pb2 as protobufs_dot_MessageComponents__pb2
from protobufs import Objects_pb2 as protobufs_dot_Objects__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/AddFolder.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x19protobufs/AddFolder.proto\x1a!protobufs/MessageComponents.proto\x1a\x17protobufs/Objects.proto\"+\n\x10\x41\x64\x64\x46olderRequest\x12\x17\n\x06\x66older\x18\x01 \x01(\x0b\x32\x07.Folder\"N\n\x11\x41\x64\x64\x46olderResponse\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.OperationResult\x12\x17\n\x06\x66older\x18\x02 \x01(\x0b\x32\x07.FolderB,\n*me.camerongray.teamlocker.client.protobufsb\x06proto3')
  ,
  dependencies=[protobufs_dot_MessageComponents__pb2.DESCRIPTOR,protobufs_dot_Objects__pb2.DESCRIPTOR,])




_ADDFOLDERREQUEST = _descriptor.Descriptor(
  name='AddFolderRequest',
  full_name='AddFolderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='folder', full_name='AddFolderRequest.folder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=132,
)


_ADDFOLDERRESPONSE = _descriptor.Descriptor(
  name='AddFolderResponse',
  full_name='AddFolderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='AddFolderResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='folder', full_name='AddFolderResponse.folder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=212,
)

_ADDFOLDERREQUEST.fields_by_name['folder'].message_type = protobufs_dot_Objects__pb2._FOLDER
_ADDFOLDERRESPONSE.fields_by_name['result'].message_type = protobufs_dot_MessageComponents__pb2._OPERATIONRESULT
_ADDFOLDERRESPONSE.fields_by_name['folder'].message_type = protobufs_dot_Objects__pb2._FOLDER
DESCRIPTOR.message_types_by_name['AddFolderRequest'] = _ADDFOLDERREQUEST
DESCRIPTOR.message_types_by_name['AddFolderResponse'] = _ADDFOLDERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddFolderRequest = _reflection.GeneratedProtocolMessageType('AddFolderRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDFOLDERREQUEST,
  __module__ = 'protobufs.AddFolder_pb2'
  # @@protoc_insertion_point(class_scope:AddFolderRequest)
  ))
_sym_db.RegisterMessage(AddFolderRequest)

AddFolderResponse = _reflection.GeneratedProtocolMessageType('AddFolderResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDFOLDERRESPONSE,
  __module__ = 'protobufs.AddFolder_pb2'
  # @@protoc_insertion_point(class_scope:AddFolderResponse)
  ))
_sym_db.RegisterMessage(AddFolderResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*me.camerongray.teamlocker.client.protobufs'))
# @@protoc_insertion_point(module_scope)
