# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/GetFolder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobufs import MessageComponents_pb2 as protobufs_dot_MessageComponents__pb2
from protobufs import Objects_pb2 as protobufs_dot_Objects__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/GetFolder.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x19protobufs/GetFolder.proto\x1a!protobufs/MessageComponents.proto\x1a\x17protobufs/Objects.proto\"O\n\x11GetFolderResponse\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.OperationResult\x12\x18\n\x07\x66olders\x18\x02 \x03(\x0b\x32\x07.FolderB,\n*me.camerongray.teamlocker.client.protobufsb\x06proto3')
  ,
  dependencies=[protobufs_dot_MessageComponents__pb2.DESCRIPTOR,protobufs_dot_Objects__pb2.DESCRIPTOR,])




_GETFOLDERRESPONSE = _descriptor.Descriptor(
  name='GetFolderResponse',
  full_name='GetFolderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='GetFolderResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='folders', full_name='GetFolderResponse.folders', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=168,
)

_GETFOLDERRESPONSE.fields_by_name['result'].message_type = protobufs_dot_MessageComponents__pb2._OPERATIONRESULT
_GETFOLDERRESPONSE.fields_by_name['folders'].message_type = protobufs_dot_Objects__pb2._FOLDER
DESCRIPTOR.message_types_by_name['GetFolderResponse'] = _GETFOLDERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFolderResponse = _reflection.GeneratedProtocolMessageType('GetFolderResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETFOLDERRESPONSE,
  __module__ = 'protobufs.GetFolder_pb2'
  # @@protoc_insertion_point(class_scope:GetFolderResponse)
  ))
_sym_db.RegisterMessage(GetFolderResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*me.camerongray.teamlocker.client.protobufs'))
# @@protoc_insertion_point(module_scope)
