# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/GetUsers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobufs import MessageComponents_pb2 as protobufs_dot_MessageComponents__pb2
from protobufs import Objects_pb2 as protobufs_dot_Objects__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/GetUsers.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18protobufs/GetUsers.proto\x1a!protobufs/MessageComponents.proto\x1a\x17protobufs/Objects.proto\"J\n\x10GetUsersResponse\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.OperationResult\x12\x14\n\x05users\x18\x02 \x03(\x0b\x32\x05.UserB,\n*me.camerongray.teamlocker.client.protobufsb\x06proto3')
  ,
  dependencies=[protobufs_dot_MessageComponents__pb2.DESCRIPTOR,protobufs_dot_Objects__pb2.DESCRIPTOR,])




_GETUSERSRESPONSE = _descriptor.Descriptor(
  name='GetUsersResponse',
  full_name='GetUsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='GetUsersResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='users', full_name='GetUsersResponse.users', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=162,
)

_GETUSERSRESPONSE.fields_by_name['result'].message_type = protobufs_dot_MessageComponents__pb2._OPERATIONRESULT
_GETUSERSRESPONSE.fields_by_name['users'].message_type = protobufs_dot_Objects__pb2._USER
DESCRIPTOR.message_types_by_name['GetUsersResponse'] = _GETUSERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetUsersResponse = _reflection.GeneratedProtocolMessageType('GetUsersResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERSRESPONSE,
  __module__ = 'protobufs.GetUsers_pb2'
  # @@protoc_insertion_point(class_scope:GetUsersResponse)
  ))
_sym_db.RegisterMessage(GetUsersResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*me.camerongray.teamlocker.client.protobufs'))
# @@protoc_insertion_point(module_scope)
